---
- name: copying the file
  hosts: all
  gather_facts: true
  vars:
    win: ['Microsoft Windows Server 2016 Datacenter',
          'Microsoft Windows Server 2022 Datacenter',
          'Microsoft Windows Server 2019 Datacenter']
  tasks:
  
    - name: started copying the file
      win_copy:
        src: /home/ubuntu/ansible/copy.txt
        dest: C:/Users/Administrator/Desktop/copy.text
        state: present
      when: ansible_distribution in win


