---
- name: Check OS version on remote machines
  hosts: all  # Replace 'all' with a specific group, e.g., 'win' or 'linux'
  tasks:
    - name: Gather system facts
      ansible.builtin.setup:

    - name: Display OS version
      debug:
        msg: "The operating system is {{ ansible_distribution }} " #{{ ansible_distribution_version }}"
