---
- name: Run tasks on multiple Windows hosts
  hosts: windows  # Specify the group of Windows hosts from your inventory
  tasks:
    - name: Checking available disk space on Windows
      win_shell: "Get-PSDrive -PSProvider FileSystem"
      register: space

    - name: Printing the space
      debug:
        msg: "{{ space.stdout_lines }}"
      when: space is defined
